// <auto-generated />
using System;
using J.Calculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace J.Calculator.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    [Migration("20210629181609_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("J.Calculator.Models.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FkId")
                        .HasColumnType("int");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("J.Calculator.Models.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContainerNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("J.Calculator.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("J.Calculator.Models.Charge", b =>
                {
                    b.HasOne("J.Calculator.Models.Container", null)
                        .WithMany("Charges")
                        .HasForeignKey("ContainerId");

                    b.HasOne("J.Calculator.Models.Invoice", null)
                        .WithMany("Charges")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("J.Calculator.Models.Invoice", b =>
                {
                    b.HasOne("J.Calculator.Models.Container", null)
                        .WithMany("Invoices")
                        .HasForeignKey("ContainerId");
                });

            modelBuilder.Entity("J.Calculator.Models.Container", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("J.Calculator.Models.Invoice", b =>
                {
                    b.Navigation("Charges");
                });
#pragma warning restore 612, 618
        }
    }
}
